In [17]:
import os
import pandas as pd
import numpy as np


BASE_DIR = "/Users/kelstonchen/GitRepos/f1-driver-performance"
INPUT_DIR = os.path.join(BASE_DIR, 'data', 'intermediate')

In [20]:
results = pd.read_csv(os.path.join(INPUT_DIR, 'results', 'results.csv'))

results.head()

,number,position,positionText,points,grid,laps,status,Driver.driverId,Driver.permanentNumber,Driver.code,...,FastestLap.Time.time,FastestLap.AverageSpeed.units,FastestLap.AverageSpeed.speed,season,round,circuit,locality,country,lat,long
0,16,1,1,26,1,57,Finished,leclerc,16,LEC,...,1:34.570,kph,206.018,2022,1,bahrain,Sakhir,Bahrain,26.0325,50.5106
1,55,2,2,18,3,57,Finished,sainz,55,SAI,...,1:35.740,kph,203.501,2022,1,bahrain,Sakhir,Bahrain,26.0325,50.5106
2,44,3,3,15,5,57,Finished,hamilton,44,HAM,...,1:36.228,kph,202.469,2022,1,bahrain,Sakhir,Bahrain,26.0325,50.5106
3,63,4,4,12,9,57,Finished,russell,63,RUS,...,1:36.302,kph,202.313,2022,1,bahrain,Sakhir,Bahrain,26.0325,50.5106
4,20,5,5,10,7,57,Finished,kevin_magnussen,20,MAG,...,1:36.623,kph,201.641,2022,1,bahrain,Sakhir,Bahrain,26.0325,50.5106

In [19]:
last_season = results.loc[results['season'] == 2025]
driver_rankings = last_season.groupby('Driver.driverId', as_index=False)['points'].sum().sort_values(by='points', ascending=False)

In [13]:
driver_rankings

   Driver.driverId  points
14          norris     394
13  max_verstappen     389
16         piastri     381
17         russell     289
12         leclerc     225
2        antonelli     135
9         hamilton     135
0            albon      70
18           sainz      54
1           alonso      51
10      hulkenberg      51
8           hadjar      50
3          bearman      39
11          lawson      38
15            ocon      34
19          stroll      29
20         tsunoda      21
7            gasly      20
4        bortoleto      19
6           doohan       0
5        colapinto       0